# permissions for end users to edit podsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podset-operator
    app.kubernetes.io/managed-by: kustomize
  name: podset-editor-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - podsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - podsets/status
  verbs:
  - get
